export const STM_ROUTES: Record<string, string> = {
  "1": "Ligne Verte",
  "2": "Ligne Orange",
  "4": "Ligne Jaune",
  "5": "Ligne Bleue",
  "10": "De Lorimier",
  "11": "Parc-du-Mont-Royal / Ridgewood",
  "12": "Île-des-Sœurs",
  "13": "Christophe-Colomb",
  "14": "Atateken",
  "15": "Sainte-Catherine",
  "16": "Graham",
  "17": "Décarie",
  "18": "Beaubien",
  "19": "Chabanel / Camp-de-Jour",
  "22": "Notre-Dame",
  "24": "Sherbrooke",
  "25": "Angus",
  "27": "Boulevard Saint-Joseph",
  "28": "Honoré-Beaugrand",
  "29": "Rachel",
  "30": "Saint-Denis / Saint-Hubert",
  "31": "Saint-Denis",
  "33": "Langelier",
  "34": "Sainte-Catherine",
  "35": "Griffintown",
  "36": "Monk",
  "37": "Jolicoeur",
  "39": "Des Grandes-Prairies",
  "41": "Quartier Saint-Michel / Ahuntsic",
  "43": "Monselet",
  "44": "Armand-Bombardier",
  "45": "Papineau",
  "46": "Casavant",
  "47": "Masson",
  "48": "Perras",
  "49": "Maurice-Duplessis",
  "51": "Édouard-Montpetit",
  "55": "Boulevard Saint-Laurent",
  "61": "Wellington",
  "63": "Girouard",
  "66": "The Boulevard",
  "67": "Saint-Michel",
  "68": "Pierrefonds",
  "69": "Gouin",
  "71": "Du Centre",
  "73": "Dalton",
  "74": "Bridge",
  "75": "De la Commune",
  "80": "Avenue du Parc",
  "85": "Hochelaga",
  "90": "Saint-Jacques",
  "92": "Jean-Talon Ouest",
  "93": "Jean-Talon",
  "94": "D'Iberville",
  "97": "Avenue-du-Mont-Royal",
  "100": "Crémazie",
  "103": "Monkland",
  "104": "Cavendish",
  "105": "Sherbrooke",
  "106": "Newman",
  "112": "Airlie",
  "113": "Lapierre",
  "119": "Rockland",
  "121": "Sauvé / Côte-Vertu",
  "124": "Victoria",
  "129": "Côte-Sainte-Catherine",
  "139": "Pie-IX",
  "141": "Jean-Talon Est",
  "144": "Avenue des Pins",
  "150": "René-Lévesque",
  "161": "Van Horne",
  "162": "Westminster",
  "165": "Côte-des-Neiges",
  "166": "Queen-Mary",
  "187": "René-Lévesque",
  "189": "Notre-Dame",
  "192": "Robert",
  "193": "Jarry",
  "195": "Sherbrooke / Notre-Dame",
  "197": "Rosemont",
  "211": "Bord-du-Lac",
  "427": "Express Saint-Joseph",
  "445": "Express Papineau",
  "465": "Express Côte-des-Neiges",
  "747": "YUL Aéroport Montréal-Trudeau / Centre-ville",
  "903": "Express Lac-Prévost"
};
